apiVersion: v1
kind: LimitRange
metadata:
  name: team-a-dev-limits
  namespace: team-a-dev-quota
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: "1"
        memory: 1Gi

