apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "globomantics-website.fullname" . }}-config"
  labels:
    app.kubernetes.io/name: "{{ include "globomantics-website.name" . }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  DB_HOST: "{{ .Values.config.dbHost }}"
  DB_PORT: "{{ .Values.config.dbPort }}"
  DB_NAME: "{{ .Values.config.dbName }}"
  DB_USER: "{{ .Values.config.dbUser }}"


