apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: private-registry-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: app
        image: ghcr.io/rummens/pluralsight-globomantics-private-registry:v3
        imagePullPolicy: Always
#      imagePullSecrets:
#        - name: ghcr-secret