apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-shared-pvc
  namespace: storageclass-csi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 1Gi