apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
  namespace: globomantics
  labels:
    demo: bottleneck
spec:
  restartPolicy: Always
  containers:
  - name: hog
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    resources:
      limits:
        memory: 64Mi
