apiVersion: v1
kind: Pod
metadata:
  name: memory-hog
  namespace: globomantics
  labels:
    demo: bottleneck
spec:
  restartPolicy: Always
  containers:
  - name: hog
    image: registry.access.redhat.com/ubi9/python-39
    command: ["python3", "-c"]
    args:
      - |
        import time
        chunks = []
        while True:
            chunks.append(bytearray(10 * 1024 * 1024))  # +10 MiB
            time.sleep(0.5)
    resources:
      limits:
        memory: 64Mi