apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: website
          image: ghcr.io/rummens/pluralsight-globomantics-website:v3

