apiVersion: v1
kind: Pod
metadata:
  name: oversized
  namespace: globomantics
spec:
  containers:
  - name: oversized
    image: registry.access.redhat.com/ubi9/ubi-minimal
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "900Gi"
