apiVersion: v1
kind: Secret
metadata:
  name: quay-pull-secret
  namespace: globomantics-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnbG9ib21hbnRpY3MtcXVheS1xdWF5LXF1YXktZW50ZXJwcmlzZS5hcHBzLm9jcC10ZXN0LmRlbW8ucnVtbWVucy5kZSI6eyJ1c2VybmFtZSI6Imdsb2JvbWFudGljcyIsInBhc3N3b3JkIjoiZ2xvYm9tYW50aWNzLWRlbW8tcHciLCJhdXRoIjoiWjJ4dlltOXRZVzUwYVdOek9tZHNiMkp2YldGdWRHbGpjeTFrWlcxdkxYQjMifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: globomantics-app
imagePullSecrets:
  - name: quay-pull-secret
