apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-demo-kernelarg
spec:
  kernelArguments:
    - systemd.unified_cgroup_hierarchy=1
