apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oadp.labels" . | nindent 4 }}
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ .Values.bsl.credentials.accessKey }}
    aws_secret_access_key={{ .Values.bsl.credentials.secretKey }}
