apiVersion: v1
kind: Pod
metadata:
  name: buildah-custom
  namespace: buildah-demo
spec:
  serviceAccountName: buildah-custom-sa
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  containers:
  - name: buildah
    image: quay.io/buildah/stable:latest
    volumeMounts:
      - mountPath: /usr/lib/containers/storage
        name: storage
    command: ["/bin/bash"]
    args: ["-c", "while true; do sleep 30; done"]
    env:
    - name: BUILDAH_ISOLATION
      value: "chroot"
    - name: STORAGE_DRIVER
      value: "vfs"
  volumes:
  - name: storage
    emptyDir: {}

