apiVersion: v1
kind: Pod
metadata:
  name: demo-cm
  namespace: demo-b
spec:
  containers:
    - name: app
      image: registry.access.redhat.com/ubi9/ubi-minimal
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo $APP_MODE;
          sleep 3600
      env:
        - name: APP_MODE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_MODE