apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-wildcard
  namespace: openshift-ingress
spec:
  secretName: globomantics-ingress-cert
  dnsNames:
    - "*.apps.test.ocp.globomantics.com"
  issuerRef:
    name: demo-ca-issuer
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
