apiVersion: v1
kind: Pod
metadata:
  name: signed-test
  namespace: globomantics-app
spec:
  restartPolicy: Never
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: signed-test
      image: globomantics-quay-quay-quay-enterprise.apps.ocp-test.demo.rummens.de/globomantics/website:v2.0
      imagePullPolicy: Always
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
