apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: troubleshooting-pvcs
spec:
  securityContext:
    runAsUser: 1001
  containers:
    - name: app
      image: registry.access.redhat.com/ubi9/ubi-minimal
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Trying to write...";
          touch /data/testfile;
          sleep 3600
      volumeMounts:
        - mountPath: /data
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: demo-pvc